import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex items-center justify-between px-16 h-[75px] border-bottom-black border">
          <Link href="/">RB</Link>
          <nav className="flex">
            <ul className="flex gap-4">
              <li>
                <Link href="/" >Home</Link>
                </li>
              <li>
                <Link href="/sobre" >Sobre</Link>
                </li>
              <li>
                <Link href="/conhecimento" >Conhecimento em</Link>
                </li>
              <li>
                <Link href="/projetos" >Projetos</Link>
                </li>
              <li>
                <Link href="/contato" >Contato</Link>
                </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
